const resources = [
  {cat:'Church', key:'church', title:'Church Membership', slug:'church-membership', desc:'A biblical framework for membership, belonging, commitment, accountability, and life together.'},
  {cat:'Spiritual Life', key:'spiritual', title:'Inner Healing', slug:'inner-healing', desc:'A careful biblical framework for evaluating inner-healing language, suffering, sanctification, prayer, and pastoral care.'},
  {cat:'Spiritual Life', key:'spiritual', title:'Demons & Angels', slug:'demons-and-angels', desc:'What Scripture teaches about angels, Satan, demons, spiritual warfare, and Christian discernment.'},
  {cat:'Biblical Studies', key:'biblical', title:'Biblical Theology', slug:'biblical-theology', desc:'Tracing the Bible’s unified storyline, themes, covenants, promises, and fulfillment in Christ.'},
  {cat:'Biblical Studies', key:'biblical', title:'Systematic Theology', slug:'systematic-theology', desc:'Organizing the Bible’s teaching into coherent doctrines for the life and ministry of the church.'},
  {cat:'Biblical Studies', key:'biblical', title:'Hermeneutics', slug:'hermeneutics', desc:'Principles and practices for interpreting Scripture faithfully in context.'},
  {cat:'Preaching', key:'leadership', title:'Homiletics', slug:'homiletics', desc:'Training for biblical preaching, sermon preparation, structure, delivery, and application.'},
  {cat:'Mission', key:'church', title:'Church Planting', slug:'church-planting', desc:'Biblical and practical resources for planting, establishing, and multiplying faithful churches.'},
  {cat:'Discipleship', key:'church', title:'Discipleship', slug:'discipleship', desc:'Resources for making disciples, teaching obedience, spiritual formation, and life together.'},
  {cat:'Pastoral Care', key:'spiritual', title:'Pastoral Care', slug:'pastoral-care', desc:'Biblical guidance for shepherding people through suffering, sin, conflict, grief, and growth.'},
  {cat:'Spiritual Life', key:'spiritual', title:'Spiritual Warfare', slug:'spiritual-warfare', desc:'A Scripture-centered approach to spiritual conflict, prayer, temptation, and discernment.'},
  {cat:'Church', key:'church', title:"The Lord's Supper", slug:'lords-supper', desc:'Biblical teaching on communion, remembrance, proclamation, fellowship, and the life of the church.'},
  {cat:'Church', key:'church', title:'Tithing & Giving', slug:'tithing-and-giving', desc:'Biblical teaching on generosity, stewardship, giving, support for ministry, and care for the needy.'},
  {cat:'Pastoral Care', key:'spiritual', title:'Spiritual Abuse', slug:'spiritual-abuse', desc:'Resources for recognizing unhealthy spiritual authority, manipulation, coercion, and restoring healthy church leadership.'},
  {cat:'Pastoral Care', key:'spiritual', title:'Church Hurt', slug:'church-hurt', desc:'Biblical and pastoral resources for people processing wounds, disappointment, conflict, and suffering in church life.'}
];
const grid=document.querySelector('#resourceGrid'),search=document.querySelector('#search'),category=document.querySelector('#category');
function render(){const q=search.value.trim().toLowerCase(),c=category.value;const filtered=resources.filter(r=>(c==='all'||r.key===c)&&[r.cat,r.title,r.desc].join(' ').toLowerCase().includes(q));grid.innerHTML=filtered.map(r=>`<article class="resource"><span class="tag">${r.cat}</span><h3>${r.title}</h3><p>${r.desc}</p><a class="bottom" href="resources/${r.slug}.html">LEARN MORE →</a></article>`).join('')||'<p>No resources found yet.</p>';}
search.addEventListener('input',render);category.addEventListener('change',render);render();
const menuBtn=document.querySelector('#menuBtn'),nav=document.querySelector('#siteNav');menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('menu-open');menuBtn.setAttribute('aria-expanded',open)});
const langBtn=document.querySelector('#langBtn'),langMenu=document.querySelector('#langMenu');langBtn.addEventListener('click',()=>{const open=langMenu.classList.toggle('open');langBtn.setAttribute('aria-expanded',open)});document.addEventListener('click',e=>{if(!langMenu.contains(e.target)&&!langBtn.contains(e.target))langMenu.classList.remove('open')});langMenu.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{langBtn.innerHTML=`${b.dataset.lang} <span>⌄</span>`;langMenu.classList.remove('open');alert(`${b.textContent} is selected. Translated resource content can be added as each resource is reviewed.`)}));
