const resources=[
{id:1,cat:'Church',key:'church',title:'Church Membership',desc:'A biblical framework for membership, belonging, commitment, accountability, and life together.',items:['Why local-church membership matters','Biblical marks of belonging and commitment','Questions for prospective members','Practical next steps for a church']},
{id:2,cat:'Church',key:'church',title:'Church Discipline',desc:'A pastoral guide to correction, restoration, repentance, and protecting the church.',items:['Matthew 18 and the church','Private correction and escalation','Restoration and repentance','Practical pastoral safeguards']},
{id:3,cat:'Leadership',key:'leadership',title:'The Elder Process',desc:'From qualifications in 1 Timothy 3 and Titus 1 to examination, plurality, appointment, and accountability.',items:['Biblical qualifications','Candidate development','Examination and affirmation','Appointment and ongoing oversight']},
{id:4,cat:'Leadership',key:'leadership',title:'Developing Elders',desc:'A practical pathway for identifying, mentoring, evaluating, and shepherding future elders.',items:['Recognizing potential leaders','Character and doctrine','Mentoring and ministry practice','Evaluation and feedback']},
{id:5,cat:'Spiritual Life',key:'spiritual',title:'“Inner Healing” Examined',desc:'A careful biblical framework for evaluating inner-healing language, suffering, sanctification, prayer, and pastoral care.',items:['Definitions and common claims','Sanctification and the Christian life','Prayer, suffering, and pastoral care','Questions churches can ask']},
{id:6,cat:'Spiritual Life',key:'spiritual',title:'Angels & Demons',desc:'What Scripture teaches about angels, Satan, demons, spiritual warfare, and Christian discernment.',items:['Biblical teaching on angels','Satan and demonic powers','Spiritual warfare in the New Testament','Discernment without speculation']},
{id:7,cat:'Biblical Studies',key:'biblical',title:'Union with Christ',desc:'A Scripture-rich introduction to the believer’s identity, life, holiness, and hope in Christ.',items:['What union with Christ means','Justification and sanctification','Life in Christ','Hope and perseverance']},
{id:8,cat:'Biblical Studies',key:'biblical',title:'Sola Scriptura',desc:'Why Scripture is sufficient and authoritative for the faith and practice of the church.',items:['Authority and inspiration','Sufficiency and clarity','Scripture and church tradition','Applying Scripture faithfully']},
{id:9,cat:'Church',key:'church',title:'Membership Interview Guide',desc:'Questions and conversation prompts for pastors and elders welcoming prospective members.',items:['Personal testimony','Doctrine and gospel clarity','Church life and commitment','Expectations of membership']}
];
const grid=document.querySelector('#resourceGrid'),search=document.querySelector('#search'),category=document.querySelector('#category');
const modal=document.querySelector('#resourceModal'),modalTitle=document.querySelector('#modalTitle'),modalDesc=document.querySelector('#modalDescription'),modalCat=document.querySelector('#modalCategory'),modalList=document.querySelector('#modalList');
function render(){const q=search.value.trim().toLowerCase(),c=category.value;const filtered=resources.filter(r=>(c==='all'||r.key===c)&&[r.cat,r.title,r.desc].join(' ').toLowerCase().includes(q));grid.innerHTML=filtered.map(r=>`<article class="resource"><span class="tag">${r.cat}</span><h3>${r.title}</h3><p>${r.desc}</p><button class="bottom" data-resource="${r.id}">READ RESOURCE →</button></article>`).join('')||'<p>No resources found yet.</p>';grid.querySelectorAll('[data-resource]').forEach(b=>b.addEventListener('click',()=>openResource(Number(b.dataset.resource))));}
function openResource(id){const r=resources.find(x=>x.id===id);if(!r)return;modalCat.textContent=r.cat;modalTitle.textContent=r.title;modalDesc.textContent=r.desc;modalList.innerHTML=r.items.map(x=>`<li>${x}</li>`).join('');openModal(modal)}
function openModal(el){el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(el){el.classList.remove('open');el.setAttribute('aria-hidden','true');if(!document.querySelector('.modal.open'))document.body.style.overflow=''}
search.addEventListener('input',render);category.addEventListener('change',render);render();
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal'))));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(closeModal)});
const menuBtn=document.querySelector('#menuBtn'),nav=document.querySelector('#siteNav');menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('menu-open');menuBtn.setAttribute('aria-expanded',open)});
const langBtn=document.querySelector('#langBtn'),langMenu=document.querySelector('#langMenu');langBtn.addEventListener('click',()=>{const open=langMenu.classList.toggle('open');langBtn.setAttribute('aria-expanded',open)});document.addEventListener('click',e=>{if(!langMenu.contains(e.target)&&!langBtn.contains(e.target))langMenu.classList.remove('open')});langMenu.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{langBtn.innerHTML=`${b.dataset.lang} <span>⌄</span>`;langMenu.classList.remove('open');alert(`${b.textContent} is selected. Translated resource content can be added as each resource is reviewed.`)}));
const formModal=document.querySelector('#formModal');document.querySelector('#requestBtn').addEventListener('click',()=>openModal(formModal));document.querySelector('#contributeBtn').addEventListener('click',()=>openModal(formModal));document.querySelector('#ideaForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#formSuccess').hidden=false;e.target.reset()});
